---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by TF.
--- DateTime: 2018/8/25 17:45
---

local skynet = require "skynet"

skynet.start(function()
    local msg, sz = skynet.pack("AAA", 20, false)
    skynet .error("msg:", msg, "sz:", sz)
end
)