---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by TF.
--- DateTime: 2018/8/25 17:41
---

local skynet = require "skynet"
require "skynet.manager"
require "skynet.harbor"

skynet.start(function ()
    skynet.error("aaaaaaa")
end)