---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by TF.
--- DateTime: 2018/9/2 17:42
---

local skynet = require "skynet"

local function dump(res, tab)
    tab = tab or 0
    if(tab == 0) then
        skynet.error("............dump...........")
    end
    if type(res) == "table" then
        skynet.error(string.rep("\t", tab).."{")
        for k,v in pairs(res) do
            if type(v) == "table" then
                dump(v, tab + 1)
            else
                skynet.error(string.rep("\t", tab), k, "=", v, ",")
            end
        end
        skynet.error(string.rep("\t", tab).."}")
    else
        skynet.error(string.rep("\t", tab) , res)
    end
end

local dog = {}

function task()
    local r = skynet.call(".DBOP", "lua", "query", "select * from dogs")
    dump(r)
    skynet.exit()
end

skynet.start(function()
    skynet.fork(task)
end)